### ISSUE TITLE
Abklärung Aufwand WMS/WMTS-Browser

### ISSUE THREAD

**Issue by nOester** [swissgeol/ngm#1397]
**Beschreibung**
WMS/WMTS Services können als zusätzliche Datenquelle in den Viewer integriert werden. Das Hinzufügen erfolgt über einen Browser, ähnlich wie bei map.geo.admin.ch
![Image](https://github.com/user-attachments/assets/77e51e34-d8a8-414b-9644-686cb3b48cc7)

Funktionen
- Es soll eine Service-URL (WMS/WMTS) eingegeben werden können
- Zu der eingegebenen URL werden die im Service enthaltenen Layer angezeigt
- Es können beliebige Layer ausgewählt werden, die dann im Datenkatalog angezeigt werden

**ToDos**
- [ ] Aufwand für die Entwicklung eines solchen Browsers prüfen
- [ ] Design für den Browser erstellen --> **Folgtask**
- [ ] Browser entwickeln --> **Folgtask**

**Acceptance Criteria**
- [ ] Der Aufwand ist geklärt, so dass die Arbeiten seitens @nOester  priorisiert wernde können

**Comment by vej-ananas** [comment]
Wir schätzen einen Aufwand von 8 SP.
